### ISSUE TITLE
Call method on load images

### ISSUE THREAD

**Issue by cristianalonso** [kevinongko/vue-instagram#31]
Hi Kevin, thanks for the plugin, it works perfect.

I need to call a method when all the photos are already loaded, any ideas??

Thank you!

**Comment by RaniaLM** [comment]
Hi!
I have the same issue, did you find the solution?

**Comment by CristianShannon** [comment]
Hi!
Sorry, no. Likewise, since the change in the intagram api since June, the plugin no longer works.
Fix it with Elfight instagram feed for quick dev. Sign up for free and you can have up to 200 free views.

Html code

`<div class="elfsight-app-YOUR-API-KEY"/>`

In beforeMount Lifecycle Hook

`beforeMount () {
    const scripts = [
      'https://apps.elfsight.com/p/platform.js'
    ]
    scripts.forEach((script) => {
      const tag = document.createElement('script')
      tag.setAttribute('src', script)
      document.head.appendChild(tag)
    })
  }`

**Comment by kevinongko** [comment]
Currently this library is unusable because of API changes, sorry :(
